apiVersion: apps/v1
kind: Deployment
metadata:
  name: aof-k8s-web-deployment
  labels:
    app: aof-k8s-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aof-k8s-web-deployment
  template:
    metadata:
      labels:
        app: aof-k8s-web-deployment
    spec:
      containers:
      - name: aof-k8s
        image: registry.digitalocean.com/aof-k8s/aof-k8s:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: aof-k8s-web-prod-env
        env:
          - name: PORT
            value: "8001"
        ports:
        - containerPort: 8001
      imagePullSecrets:
        - name: aof-k8s  


---
apiVersion: v1
kind: Service
metadata:
  name: aof-k8s-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: aof-k8s-web-deployment