name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
 
  build:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: aof-k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Insall doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: Login to DO Container Registry with short-lived creds
        run: doctl registry login --expiry-seconds 1200
      - name: Build container image
        working-directory: ./web
        run: |
          docker build -f Dockerfile \
            -t registry.digitalocean.com/aof-k8s/aof-k8s:latest \
            -t registry.digitalocean.com/aof-k8s/aof-k8s:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .
      - name: Push image
        run: |
          docker push registry.digitalocean.com/aof-k8s/aof-k8s --all-tags
      - name: K8s cluster kubeconfig file with/ short-lived creds
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: Update deployment secrets
        run: |
          cat << EOF >> web/.env
          DEBUG=${{ secrets.DEBUG }}
          NODE_ENV=${{ secrets.NODE_ENV }}
          DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUERPUSER_EMAIL=${{ secrets.DJANGO_SUERPUSER_EMAIL }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          PGHOST=${{ secrets.PGHOST }}
          SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
          STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }}
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          WEBHOOK_KEY=${{ secrets.WEBHOOK_KEY }}
          EOF
          kubectl delete secret aof-k8s-web-prod-env
          kubectl create secret generic aof-k8s-web-prod-env --from-env-file=web/.env
      - name: Update Deployment image
        run: |
          kubectl set image deployment/aof-k8s-web-deployment aof-k8s-web=registry.digitalocean.com/aof-k8s/aof-k8s:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/aof-k8s-web-deployment
      - name: Post-build Django Commands - Migrate / Collectstatic
        run: |
          export SINGLE_POD_NAME=$(kubectl get pod -l app=aof-k8s-web-deployment -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/collectstatic.sh